### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by sigilante** [sigilante/l10n#1]
- [ ] convert to proper parser for locale strings
- [x] implement unit tests
- [ ] implement the full Unicode case folding list, https://unicode.org/Public/UCD/latest/ucd/CaseFolding.txt

**Comment by sigilante** [comment]
- [ ] switch to `mip` data structure

**Comment by sigilante** [comment]
- [ ] switch from `settings-store` to https://github.com/sigilante/global-store
